version: '3.8'

services:
  excalibur:
    image: ghcr.io/williamjacksn/excalibur
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/excalibur
    environment:
      HOST: 0.0.0.0
      PORT: 8080
