services:
  excalibur:
    image: ghcr.io/williamjacksn/excalibur
    init: true
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./.local:/home/python/excalibur
    environment:
      HOST: 0.0.0.0
      PORT: 8080
